// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_uat.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Web Client ID (client_type: 3) from google-services.json
  /// Used as serverClientId for Google Sign-In
  static const String webClientId =
      '695787289329-r5lmh0rgl7ma94f02gn3it354r70pd81.apps.googleusercontent.com';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_iJsooH7Iy8f0Oe5iX3FvEWnsuqsxY9o',
    appId: '1:695787289329:web:71cb7886b453264f9c8750',
    messagingSenderId: '695787289329',
    projectId: 'js-test-e5720',
    authDomain: 'js-test-e5720.firebaseapp.com',
    databaseURL: 'https://js-test-e5720.firebaseio.com',
    storageBucket: 'js-test-e5720.appspot.com',
    measurementId: 'G-6R30R6JYW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaiy0SmZPP4fxprzfBj818OwRfwI6lcSA',
    appId: '1:695787289329:android:3c7b691fb69929229c8750',
    messagingSenderId: '695787289329',
    projectId: 'js-test-e5720',
    databaseURL: 'https://js-test-e5720.firebaseio.com',
    storageBucket: 'js-test-e5720.appspot.com',
  );
}
